import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "~/components/cores/Navbar/Navbar";
import Footer from "~/components/cores/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Code Challenge",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className=" flex  min-h-screen w-full flex-col justify-between bg-pampas bg-blend-color-burn">
          <div className="sticky top-0 z-50">
            <Navbar />
          </div>
          <div className="flex h-max items-center justify-center lg:px-20">
            {children}
          </div>

          <Footer />
        </div>
      </body>
    </html>
  );
}
